name: "frontend:test:build test code"

on: push

jobs:
  # only (but most important) job from this workflow required for pull requests
  # check results serve as run conditions for all other jobs here
  files-changed:
    name: Detect File Changes - frontend-test-build-code
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.frontend-test-build-code }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7

      - name: Check for frontend file changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml
          list-files: shell

  build:
    if: needs.files-changed.outputs.changes == 'true'
    name: Build - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: frontend/.tool-versions

      - name: Frontend | Build
        run: npm install && npm run build
        working-directory: ${{env.WORKING_DIRECTORY}}